export const customerData = [
  {
    id: "password",
    name: "password",
    type: "text",
    label: "Password",
    autocomplete: "password",
  },
  {
    id: "email",
    name: "email",
    type: "text",
    label: "Email Address",
    autocomplete: "email",
  },
  {
    id: "company",
    name: "company",
    type: "text",
    label: "Company Name",
    autocomplete: "company",
  },
  {
    id: "username",
    name: "username",
    type: "text",
    label: "Contact Name",
    autocomplete: "contact-name",
  },
  {
    id: "phone",
    name: "phone",
    type: "text",
    label: "Phone Number",
    autocomplete: "phone",
  },
  {
    id: "address",
    name: "address",
    type: "text",
    label: "Address",
    autocomplete: "address",
  },
  {
    id: "type",
    name: "type",
    type: "text",
    label: "Customer type",
    autocomplete: "type",
  },
];
